name: Release published

on:
  release:
    types:
      - published

jobs:
  deploy_to_prod:
    name: Deploy to Production
    environment: REF_DATA_PROD
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Artifact from Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: build.zip

      - name: Unzip artifact
        run: unzip -q build.zip

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.x'
          cache: 'npm'

      - name: Rebuild npm
        run: npm rebuild

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ref-data-service-github-actions-role-eu-west-2
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy to prod
        env:
          ROOT_DOMAIN: ${{ vars.ROOT_DOMAIN }}
          PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}
        run: |
          npm run sst -- deploy --stage prod
