name: Pull Request Opened / Updated

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.x'
          cache: 'npm'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test API
        run: npm run test:unit -w @reference-data-service/api

      - name: Test reference data uploaders
        run: |
          cd packages/ref-data-uploaders/txc-uploader
          pip install -r requirements.test.txt
          echo "Running tests..."
          python3 -m pytest tests/
