name: Pull Request Opened / Updated

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test TypeScript compiles
        run: npm run tsc:build

      - name: Tests Node.js
        run: |
          npm run test

      - name: Tests Python
        run: |
          cd packages/ref-data-uploaders/txc-uploader
          pip install -r requirements.test.txt
          echo "Running tests..."
          python3 -m pytest tests/
